// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupremeCourtRecords.Models;

#nullable disable

namespace SupremeCourtRecords.Migrations
{
    [DbContext(typeof(CaseContext))]
    partial class CaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SupremeCourtRecords.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JudgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetitionerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RespondentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CaseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("PetitionerId");

                    b.HasIndex("RespondentId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Judge", b =>
                {
                    b.Property<int>("JudgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("JudgeId");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Petitioner", b =>
                {
                    b.Property<int>("PetitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PetitionerId");

                    b.ToTable("Petitioners");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Respondent", b =>
                {
                    b.Property<int>("RespondentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("RespondentId");

                    b.ToTable("Respondents");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Case", b =>
                {
                    b.HasOne("SupremeCourtRecords.Models.Category", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupremeCourtRecords.Models.Judge", "Judge")
                        .WithMany("Cases")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupremeCourtRecords.Models.Petitioner", "Petitioner")
                        .WithMany("Cases")
                        .HasForeignKey("PetitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupremeCourtRecords.Models.Respondent", "Respondent")
                        .WithMany("Cases")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Judge");

                    b.Navigation("Petitioner");

                    b.Navigation("Respondent");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Category", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Judge", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Petitioner", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("SupremeCourtRecords.Models.Respondent", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
